
// src/locales/en/faqPage.ts
import type { Translations } from '@/contexts/LocalizationContext';

export const faqPageEnTranslations: Partial<Translations> = {
  faq_PageTitle: "User Guide",
  faq_PageDescription: "Find answers and learn how to use the PowerLog application.",
  faq_chapter_introduction_title: "1. Introduction",
  faq_chapter_introduction_content: "Welcome to PowerLog! This application is designed to help you quickly calculate and compare logistics costs for different shipping modes, primarily focusing on \"Sea + Rail\" and \"Direct Rail\" options. It leverages data from your uploaded Excel files and can provide AI-generated commentary and identify the most cost-effective routes.",
  faq_chapter_gettingStarted_title: "2. Getting Started: Uploading Data Files",
  faq_chapter_gettingStarted_content: "PowerLog relies on data from three specific Excel files. These files should be uploaded via the buttons at the top of the main Calculator page:\n\n*   **Sea + Rail Button:** Uploads the main Excel file containing:\n    1.  Sheet 1 (Dashboard Data): Pre-defined service rates from various sea lines, including potential railway leg information. This data populates the \"Dashboard\" page.\n    2.  Sheet 2 (SOC Sea Routes): Pricing for \"Shipper Owned Container\" (SOC) sea routes.\n    3.  Sheet 3 (COC Sea Routes): Pricing for \"Carrier Owned Container\" (COC) sea routes.\n    4.  Sheet 4 (COC Drop-Off Costs): Costs associated with dropping off COC containers.\n    5.  Sheet 5 (Rail Data): Detailed pricing for railway segments, including costs for different container types and guard services.\n    *   When to Upload: Upload this file first or whenever your Sea+Rail rates, dashboard services, or rail data changes.\n    *   Impact: Populates the Dashboard page and provides the core data for \"Sea + Rail\" calculations.\n\n*   **Direct Rail Button:** Uploads an Excel file specifically containing rates and details for direct railway shipments.\n    *   When to Upload: Upload this if you work with direct rail options or when this data is updated.\n    *   Impact: Enables calculations and \"Best Price\" options for the \"Direct Rail\" mode.\n\n*   **SOC Drop-Off Button:** Uploads an Excel file containing specific drop-off costs for \"Shipper Owned Containers\" (SOC).\n    *   When to Upload: Upload this if you handle SOC shipments and have separate drop-off pricing for them.\n    *   Impact: Provides necessary data for accurate SOC shipment calculations, especially when determining total costs.\n\n**Important Notes on Uploading:**\n*   The buttons will show \"Processing...\" while a file is being uploaded and parsed.\n*   Toast notifications will appear to confirm successful parsing or to indicate errors.\n*   Uploading a new file for a specific type (e.g., Sea+Rail) will replace the previously loaded data for that type.",
  faq_chapter_calculatorPage_title: "3. The Calculator Page (Main Form)",
  faq_chapter_calculatorPage_content: "This is your primary workspace for calculating individual shipping quotes and finding the best prices.\n\n**Selecting Calculation Mode:**\n*   Use the radio buttons (\"Sea + Rail\" / \"Direct Rail\") to choose your calculation type. Changing modes adjusts the form fields.\n\n**Understanding Form Fields:**\n*   Exchange Rate Display: Shows the current USD/RUB rate.\n*   Sea Margin / Rail Margin: Add numerical margins to sea or rail costs (Sea + Rail mode only for specific price calculations).\n*   Shipment Type: COC (Carrier Owned) or SOC (Shipper Owned).\n*   Sea + Rail Fields: Origin Port, Destination Port (Sea), Sea Line Company, Container Type, Destination City (Rail), Station (Rail). Dropdown options are populated dynamically from your Excel data and filter based on previous selections.\n*   Direct Rail Fields: City of Departure, Destination City, Agent Name, Incoterms, Border. Options are also dynamic based on your Direct Rail Excel.\n\n**Getting a Price & AI Commentary Button:**\n*   Calculates a price based on the exact form inputs.\n*   Displays a \"Shipping Information\" card with cost breakdowns, Excel comments, and AI-generated insights (placeholder).\n\n**Calculating Best Prices Button:**\n*   Searches all loaded data (Sea+Rail, Direct Rail, Dashboard) for the top 6 most cost-effective routes based on your primary criteria.\n*   Navigates you to the \"Best Prices Page\" with the results.\n\n**Interpreting Results & Actions (Below Form):**\n*   Shipping Information Card: Appears after \"Get Price & Commentary\".\n*   \"Copy Full Output\" (Sea+Rail): Copies a formatted summary of the quote.\n*   \"Create Instructions\" (Sea+Rail): Navigates to the (placeholder) Instructions page with pre-filled data.\n*   \"Copy Direct Rail Info\" (Direct Rail): Copies a summary of the Direct Rail quote.",
  faq_chapter_dashboardPage_title: "4. Dashboard Page",
  faq_chapter_dashboardPage_content: "The Dashboard provides an overview of pre-defined service rates from Sheet 1 of your \"Sea + Rail Excel\" file.\n\n*   **Data Display:** Rates are grouped by \"Service Name.\" Each row shows a route, sea rate, container info, and comments.\n*   **Railway Legs:** If a service section includes rail data (often under the last sea route of that service in Excel), these common legs are shown below. You can select one railway leg by checking its box.\n*   **\"Copy Rate\" Button:** Copies a formatted string with the main route details, sea rate, and the cost of any selected railway leg for that section.",
  faq_chapter_bestPricesPage_title: "5. Best Prices Page",
  faq_chapter_bestPricesPage_content: "This page displays up to 6 top cost-effective options after you click \"Calculate Best Price.\"\n\n*   **Header:** Summarizes your search criteria.\n*   **Option Cards:** Each card represents a route.\n    *   **Dashboard-Sourced Routes:** Highlighted with a green header and a \"From Our Best\" badge. The title shows the Dashboard Service Name.\n    *   **Route Description:** Visual summary of the shipping path.\n    *   **Sea Line / Agent:** Relevant shipping line or agent.\n    *   **Route Details:** Key parameters like ports, container type, final city, stations.\n    *   **Cost Breakdown:** Includes Sea Freight, Railway Leg (if applicable and priced), and Drop Off costs. Comments from Excel are also shown.\n*   **Actions per Card:**\n    *   \"Copy Rate\": Copies a detailed cost breakdown.\n    *   \"Create Instructions\": Navigates to the Instructions page with data from this option (disabled for Direct Rail and Dashboard routes).",
  faq_chapter_instructionsPage_title: "6. Instructions Page",
  faq_chapter_instructionsPage_content: "This page is reached via the \"Create Instructions\" button. Its purpose is to pre-fill a form (currently a placeholder for future full implementation) that would be used to generate formal shipping instructions based on your calculations.",
  faq_chapter_languageSettings_title: "7. Language Settings",
  faq_chapter_languageSettings_content: "You can switch the application's interface language between English and Russian. Go to \"Settings\" in the sidebar, then select \"English\" or \"Russian\" under the Languages submenu. The entire UI will update.",
  faq_chapter_troubleshooting_title: "8. Troubleshooting & Tips",
  faq_chapter_troubleshooting_content: "*   **No Data/Options Appearing:** Ensure correct Excel files are uploaded. Verify file formats match requirements (column order, sheet names for Sea+Rail file).\n*   **Buttons Disabled:** Make sure all mandatory fields for the specific action are filled.\n*   **Incorrect Rail Costs/Missing Rail Legs:**\n    *   Confirm the Sea Destination Port (e.g., Vladivostok, Vostochny, ВМТП/ВМКТ, ВМПП/ТА, ВРАНГЕЛЬ) is recognized as a rail hub.\n    *   Ensure rail pricing data exists in your Sea+Rail Excel (Sheet 5) for the relevant departure/arrival points and container type.\n    *   If using dashboard rates like \"FOR Станции Мос. узла,\" make sure \"Destination City (Rail)\" in the form is set to \"Москва.\"\n*   **Copied Text:** The text is plain and can be pasted into emails or documents.\n*   **Dropdown Issues:** If dropdowns don't update as expected after changing a parent field, try re-selecting the parent field to refresh the options.",
};
